name: Upload to IPFS
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v7 branch
  push:
    branches: [ v7 ]
  pull_request:
    branches: [ v7 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

uses: aquiladev/ipfs-action@v0.2.1-alpha.4

with:
  path: ./build
  service: pinata
  pinataKey: 3218f055d5dfeb5729e2
  pinataSecret: 23b5a758ccaf95cbc26f887ce2285f2705a7c79857f2a00a03fe9f344c28e5ee
  
